require:
  - "standard"

inherit_gem:
  standard: "config/base.yml"

AllCops:
  TargetRubyVersion: 3.2
  # New cops introduced inbetween rubocop major versions are pending by default.
  # This option enables them. More info:
  # https://docs.rubocop.org/rubocop/versioning.html#pending-cops
  NewCops: "enable"
  SuggestExtensions: false
  Exclude:
    - "bin/*"
    - "tmp/**/*"
    - "tests/**/*"

# Lines that are too long are less legible and harder to follow.
Layout/LineLength:
  Enabled: true
  Max: 80
